# a short string to identify the bridge
Identifier = "routerswap"


# router sever config (server only)
[Server]
# administrators who can do admin work
Admins = [
	"0x3dfaef310a1044fd7d96750b42b44cf3775c00bf",
	"0x46cbe22b687d4b72c8913e4784dfe5b20fdc2b0e"
]

# chain id black list of string array
ChainIDBlackList = []

# token id black list of string array
TokenIDBlackList = []

# modgodb database connection config
[Server.MongoDB]
DBURL = "localhost:27017"
DBName = "databasename"
UserName = "username"
Password = "password"

# bridge API service
[Server.APIServer]
# listen port
Port = 11556
# CORS config
AllowedOrigins = []


[OnChain]
Contract = "0x61b8c4d6d28d5f7edadbea5456db3b4f7f836b64"
APIAddress = ["http://47.107.50.83:3002"]

# DCRM config
[Dcrm]
# dcrm group ID
GroupID = "74245ef03937fa75b979bdaa6a5952a93f53e021e0832fca4c2ad8952572c9b70f49e291de7e024b0f7fc54ec5875210db2ac775dba44448b3972b75af074d17"

# dcrm threshold (NeededOracles=2,TotalOracles=3 represent '2/3' threshold)
NeededOracles = 2
TotalOracles = 3

# dcrm mode (0:managed 1:private)
Mode = 0

# initiators of dcrm sign
Initiators = [
	"0x897a9980808a2cae0d09ff693f02a4f80abb2233"
]

# DCRM default node config
[Dcrm.DefaultNode]
# dcrm sub groups for signing (server only)
SignGroups = [
	"38a93f457c793ac3ee242b2c050a403774738e6558cfaa620fe5577bb15a28f63c39adcc0778497e5009a9ee776a0778ffcad4e95827e69efa21b893b8a78793",
	"bb1dfe1ec046cc3a3b88408ae03976aabffe459b40e5def09e76f5d4c7a917133241da9da7fc05e3e172fab54ce3129a9a492d52a5a09494d0b9c1e608f661bf"
]

# dcrm user keystore and password file (suggest using absolute path)
KeystoreFile = "/home/xxx/accounts/keystore1"
PasswordFile = "/home/xxx/accounts/password1"

# dcrm backend node (gdcrm node RPC address)
RPCAddress = "http://127.0.0.1:2921"
